# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30390097d0847a6dfea8ec3d8f51784f60bed80c2a5d1de0bb74e31ea2acbf64f4f138a75fbdb976583caf0fb6035a48a738cb207af04645bcb32e7cec7283f6

test:
  secret_key_base: 93b84e040c359ab8f34a892ca71dbd44980172918500151a46d3f3d4507c24e2a8edbad38e8bc2172e84ab486c7aa3c9a8c8ed5b5eaf39dafac6553be089abfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
