source 'https://rubygems.org'

ruby '2.2.3'

gem 'jwt'
gem 'dotenv-rails'
gem 'purecss-rails'
gem 'sucker_punch'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
gem 'almond-rails'
gem 'sass-rails', github: 'rails/sass-rails', branch: 'master'
gem 'sprockets-rails', github: 'rails/sprockets-rails', branch: 'master'
gem 'sprockets', github: 'rails/sprockets', branch: 'master'
# gem 'sprockets'
# gem 'sass-rails', '~> 5.0'
# gem 'sprockets-rails', github: 'rails/sprockets-rails', branch: 'master'
# gem 'sprockets', github: 'rails/sprockets', branch: 'master'
# gem 'sprockets-rails', '< 3.0.0'
gem 'babel-transpiler'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'spring'
end

source 'https://rails-assets.org' do
  gem 'rails-assets-almond'
end

group :production do
  gem 'rails_12factor'
  gem 'puma'
end
